# Generated by Django 3.2.9 on 2021-11-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('text', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='слово или фраза')),
                ('pos', models.CharField(blank=True, choices=[['noun', 'существительное'], ['verb', 'глагол'], ['adjective', 'прилагательное'], ['participle', 'причастие']], max_length=20, null=True, verbose_name='часть речи')),
                ('fr', models.PositiveIntegerField(blank=True, max_length=1, null=True, verbose_name='из яндекса не понятно что это')),
                ('syn', models.ManyToManyField(blank=True, max_length=100, null=True, related_name='_synonym_word_syn_+', to='synonym.Word', verbose_name='синоним')),
                ('tr', models.ManyToManyField(blank=True, max_length=100, null=True, related_name='_synonym_word_tr_+', to='synonym.Word', verbose_name='перевод / значение')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
    ]
